Revert "Fix undefined reference to a 64bit function on ext4 stack in one of the latest 3.0.y patches."
This reverts commit c7baee4fe5c982e9a7589cf44ae6017a8304d8b2.